spring:
  application:
    name: mybooking-cloud-discovery

server:
  port: 8761
  servlet:
    context-path: /mybooking/cloud-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/mybooking/cloud-discovery
